name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.13
api: 1.13
softdepends: ["PlaceholderAPI", "SwiftBoard", "NoteBlockAPI"]
softdepend:
  - "PlaceholderAPI"
  - "SwiftBoard"
  - "NoteBlockAPI"
url: ${url}
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: "This is an example plugin."
  gmc:
    description: "Switch to creative mode."
  gms:
    description: "Switch to survival mode."
  fly:
    description: "Toggle flight."
  build:
    description: "Enable admin build mode."